### ISSUE TITLE
FIPS 180-4 

### ISSUE THREAD

**Issue by mjenrungrot** [fangherk/MicroPCoin#1]
Todo
- [x] Testbench for SHA-256
- [x] Implement Ch(x,y,z) Eq. 4.2
- [x] Testbench for Eq 4.2
- [x] Implement Maj(x,y,z) Eq 4.2=3
- [x] Testbench for Eq 4.3
- [x] Implement Eq 4.4
- [x] Testbench for Eq 4.4
- [x] Implement Eq 4.5
- [x] Testbench for Eq 4.5
- [x] Implement Eq 4.6
- [x] Testbench for Eq 4.6
- [x] Implement Eq 4.7
- [x] Testbench for Eq 4.7
- [x] Get SHA-256 constants into file
- [x] Hash Computation
- - [x] Preprocessing
- - - [x] Set the initial hash value, H^(0), as specified in Section 5.3.3
- - - [x] Message is padded and parsed as specified in Section 5.
- - [x] Hash Computation
- - - [x] Step 1 Implementation
- - - [x] Step 2 Implementation
- - - [x] Step 3 Implementation
- - - [x] Step 4 Implementation
- - - [x] Repeat n steps
- - [x] Test

- [x] Optimize preparedMessage to cut down logic elements

**Comment by mjenrungrot** [comment]
Section 4.1.2 SHA-256 functions
Section 4.2.2 SHA-256 constants

**Comment by fangherk** [comment]
Section 3.2
ROTR function
SHR function
ROTL function

**Comment by mjenrungrot** [comment]
Section 3.1
For SHA-256, each message block has 512 bit, which are represented as a sequence of 16 32-bit words.

**Comment by fangherk** [comment]
Padding the Message 5.1.1, done on the Pi
0. get length of message M as l bits, so 1 byte per char. 
a. append each char in bytes
b. Append the bit ``1'' to the end of the message, followed by k zero bits such that l + 1 + k === 448 mod 51.
c. Append 64-bit block equal to the number l expressed using binary representation.

**Comment by fangherk** [comment]
Testbench Test Vectors based off of NIST test vectors and consultancy's test vectors:
https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/secure-hashing#shavs
https://www.di-mgt.com.au/sha_testvectors.html
