### ISSUE TITLE
Server Stuff

### ISSUE THREAD

**Issue by mjenrungrot** [fangherk/MicroPCoin#2]
Todo
- [x] Setup a Raspberry Pi server
- [x] Setup a Flask server
- [x] Test Flask with Python

Overview:
- [x] Test Practice Rig.  
- [x] Block Diagram Our System Design
- [x] Choose Tools: Apache, Django, Other Web Servers, etc.
- [x] Game plan for completion 
- [x] Writeup for things done.

**Comment by fangherk** [comment]
https://github.com/conradoqg/naivecoin
